#!/usr/bin/env python3
# -*- coding: utf-8 -*-
exec(open("tools/gen_tpe_seo.py").read().split("\nn=0")[0])  # ACT, page

P=[
 # --- secteurs ---
 ("meilleur-tpe-fleuriste","Meilleur TPE pour fleuriste 2026 : top 4","Quel TPE pour un fleuriste en 2026 ? Top 4 des terminaux adaptés (encaissement rapide, livraison). Flatpay, Square, SumUp, myPOS.","Meilleur TPE pour fleuriste : le top 4 en 2026","Fleuriste : encaissements en boutique et en livraison, paniers variés. Voici les meilleurs TPE.",["flatpay","square","sumup","mypos"]),
 ("meilleur-tpe-opticien","Meilleur TPE pour opticien 2026 : top 4","Quel TPE pour un opticien en 2026 ? Top 4 pour gérer paiements en plusieurs fois et tiers payant. Flatpay, Square, myPOS, SumUp.","Meilleur TPE pour opticien : le top 4 en 2026","Optique : paniers élevés, paiement en plusieurs fois fréquent. Voici les meilleurs TPE.",["flatpay","square","mypos","sumup"]),
 ("meilleur-tpe-pharmacie","Meilleur TPE pour pharmacie 2026 : top 4","Quel TPE pour une pharmacie en 2026 ? Top 4 des terminaux rapides et fiables pour officine. Flatpay, Square, myPOS, SumUp.","Meilleur TPE pour pharmacie : le top 4 en 2026","Pharmacie : flux important, sans-contact, fiabilité. Voici les meilleurs TPE pour officine.",["flatpay","square","mypos","sumup"]),
 ("meilleur-tpe-caviste","Meilleur TPE pour caviste 2026 : top 4","Quel TPE pour un caviste en 2026 ? Top 4 des terminaux pour cave et épicerie fine. Flatpay, Square, SumUp, myPOS.","Meilleur TPE pour caviste : le top 4 en 2026","Caviste et épicerie fine : paniers premium, dégustations, marchés. Voici les meilleurs TPE.",["flatpay","square","sumup","mypos"]),
 ("meilleur-tpe-boucherie","Meilleur TPE pour boucherie 2026 : top 4","Quel TPE pour une boucherie ou charcuterie en 2026 ? Top 4 des terminaux rapides. Flatpay, Square, SumUp, myPOS.","Meilleur TPE pour boucherie : le top 4 en 2026","Boucherie-charcuterie : encaissements rapides au comptoir et sur les marchés. Voici les meilleurs TPE.",["flatpay","square","sumup","mypos"]),
 ("meilleur-tpe-garage","Meilleur TPE pour garage auto 2026 : top 4","Quel TPE pour un garage automobile en 2026 ? Top 4 pour encaisser réparations et gros montants. Flatpay, Square, myPOS, SumUp.","Meilleur TPE pour garage auto : le top 4 en 2026","Garage : montants élevés, paiement en plusieurs fois, devis. Voici les meilleurs TPE.",["flatpay","square","mypos","sumup"]),
 ("meilleur-tpe-traiteur","Meilleur TPE pour traiteur 2026 : top 4 mobile","Quel TPE pour un traiteur en 2026 ? Top 4 des terminaux mobiles pour événements et livraisons. SumUp, Viva, Flatpay, Zettle.","Meilleur TPE pour traiteur : le top 4 en 2026","Traiteur : encaissement sur événements, en mobilité, acomptes. Voici les meilleurs TPE.",["sumup","viva-wallet","flatpay","zettle"]),
 ("meilleur-tpe-salle-de-sport","Meilleur TPE pour salle de sport 2026 : top 4","Quel TPE pour une salle de sport ou coach en 2026 ? Top 4 pour abonnements et paiements récurrents. Flatpay, Square, SumUp, myPOS.","Meilleur TPE pour salle de sport : le top 4 en 2026","Salle de sport et coaching : abonnements, paiements récurrents, accueil. Voici les meilleurs TPE.",["flatpay","square","sumup","mypos"]),
 ("meilleur-tpe-camping","Meilleur TPE pour camping 2026 : top 4","Quel TPE pour un camping ou gîte en 2026 ? Top 4 pour réception, bar et multi-points de vente. Flatpay, Square, myPOS, SumUp.","Meilleur TPE pour camping : le top 4 en 2026","Camping et hôtellerie de plein air : réception, bar, épicerie, multi-postes. Voici les meilleurs TPE.",["flatpay","square","mypos","sumup"]),
 ("meilleur-tpe-association","Meilleur TPE pour association 2026 : top 4","Quel TPE pour une association en 2026 ? Top 4 pour cotisations, buvettes et événements, sans engagement. SumUp, Viva, Zettle, Flatpay.","Meilleur TPE pour association : le top 4 en 2026","Association : cotisations, buvettes, événements ponctuels, budget serré. Voici les meilleurs TPE sans engagement.",["sumup","viva-wallet","zettle","flatpay"]),
 ("meilleur-tpe-profession-liberale","Meilleur TPE pour profession libérale 2026 : top 4","Quel TPE pour une profession libérale en 2026 ? Top 4 pour cabinets et consultations. Flatpay, SumUp, myPOS, Square.","Meilleur TPE pour profession libérale : le top 4 en 2026","Professions libérales : consultations, honoraires, simplicité. Voici les meilleurs TPE.",["flatpay","sumup","mypos","square"]),
 ("meilleur-tpe-epicerie","Meilleur TPE pour épicerie 2026 : top 4","Quel TPE pour une épicerie ou supérette en 2026 ? Top 4 des terminaux rapides. Flatpay, Square, SumUp, myPOS.","Meilleur TPE pour épicerie : le top 4 en 2026","Épicerie et supérette : flux rapide, petits paniers, sans-contact. Voici les meilleurs TPE.",["flatpay","square","sumup","mypos"]),
 # --- angles long-tail ---
 ("tpe-4g","Meilleur TPE 4G sans wifi 2026 : top 4 autonomes","Quel TPE 4G sans wifi en 2026 ? Top 4 des terminaux autonomes avec carte SIM intégrée. SumUp, Viva, myPOS, Flatpay.","Meilleur TPE 4G (sans wifi) : le top 4 en 2026","Pas de wifi ? Un TPE avec 4G intégrée encaisse partout. Voici les meilleurs terminaux autonomes.",["sumup","viva-wallet","mypos","flatpay"]),
 ("tpe-caisse-enregistreuse","Meilleur TPE avec caisse enregistreuse 2026 : top 4","Quel TPE avec caisse enregistreuse en 2026 ? Top 4 des solutions tout-en-un (encaissement + caisse). Flatpay, Square, myPOS, SumUp.","Meilleur TPE avec caisse : le top 4 en 2026","Encaissement + logiciel de caisse en une seule solution : voici les meilleurs systèmes tout-en-un.",["flatpay","square","mypos","sumup"]),
 ("louer-un-tpe","Louer un TPE en 2026 : top 4 des terminaux en location","Où louer un TPE en 2026 ? Top 4 des terminaux en location sans gros investissement. Flatpay, myPOS, SumUp, Square.","Louer un TPE : le top 4 en 2026","Plutôt que d'acheter, louez votre terminal : voici les meilleures formules de location de TPE.",["flatpay","mypos","sumup","square"]),
 ("tpe-sans-contact","Meilleur TPE sans contact 2026 : top 4 (Apple Pay, Google Pay)","Quel TPE sans contact en 2026 ? Top 4 acceptant Apple Pay, Google Pay et cartes NFC. Flatpay, SumUp, Viva, Square.","Meilleur TPE sans contact : le top 4 en 2026","Sans contact, Apple Pay, Google Pay : indispensables aujourd'hui. Voici les meilleurs TPE NFC.",["flatpay","sumup","viva-wallet","square"]),
 ("tpe-vente-a-domicile","Meilleur TPE pour vente à domicile 2026 : top 4","Quel TPE pour la vente à domicile en 2026 ? Top 4 des terminaux mobiles pour VRP et commerciaux. SumUp, Viva, myPOS, Zettle.","Meilleur TPE pour vente à domicile : le top 4 en 2026","Vente à domicile et porte-à-porte : un terminal mobile fiable est clé. Voici les meilleurs.",["sumup","viva-wallet","mypos","zettle"]),
 ("frais-tpe-comparatif","Frais de TPE 2026 : comparatif des commissions","Comparatif des frais de TPE en 2026 : commissions, abonnements, location. Flatpay, SumUp, Square, myPOS, Viva comparés.","Frais de TPE : le comparatif des commissions 2026","Commission, abonnement, location du terminal : on compare le coût réel des principaux TPE.",["flatpay","viva-wallet","square","sumup"]),
]
n=0
for slug,title,desc,h1,intro,order in P:
    open(f"comparatifs/{slug}.html","w").write(page(slug,title,desc,h1,intro,order)); n+=1
print("nouveaux comparatifs TPE:",n)
